// The Idea Manager's whole loop, once, for real — and the four seams where two
// independently-built pieces of it meet.
//
// idea-handoff-db-child.ts already drives the handoff's own decisions against a
// real Postgres, and turn-outcome-truth-db-child.ts already drives a real turn.
// Neither joins the two: every scenario in the first one hand-builds the
// `idea_runs` row a real dispatch would have produced, or stops at the moment
// `sendMessage` returns. So the things that only exist *between* those two
// files have never run — a prompt generated by the real generation worker and
// dispatched by the real sweep, an asset copied by the real handoff and then
// announced by a real turn, a real turn-ended event closing a real run, and a
// follow-up dispatch reusing the session the first one created. That gap is
// what this file is for.
//
// What is real here: Postgres, every `features/ideas/*` service call, the
// handoff sweep, `runIdeaPrompt`, `createSession`, `attachIdeaAssetsToSession`
// (bytes on disk included), `sendMessage`, `runTurn`, `endTurn`,
// `handleTurnEnded` and `closeRun`.
//
// What is faked, and why:
//   - the SDK's `query`, twice over — nothing here may reach Anthropic. The
//     two call sites are told apart by `options.outputFormat`, which only
//     features/ideas/prompt-service.ts sets (see its
//     IDEA_PROMPT_ANSWER_JSON_SCHEMA); a session turn never does. That is a
//     property of the code under test, not a flag this file passes in.
//   - BullMQ, so the queue becomes an array this file drains by hand, in the
//     order a scenario wants. `enqueueTurnEnded` -> `handleTurnEnded` is the
//     event bus the brief asks to be faked; both ends of it are real code.
//   - ioredis and lib/events.ts: Redis is not running, and `subscribeControl`
//     calls `.subscribe()` on the connection outright rather than swallowing
//     it (the same reason turn-outcome-truth-db-child.ts fakes it).
//   - runner-options.ts, which shells out to git inside a project checkout —
//     a different subsystem, and not what any assertion below is about.
//
// The child gathers facts; every assertion lives in idea-loop.test.ts.

import { randomUUID } from 'node:crypto'
import { mkdir, readdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { mock } from 'bun:test'

const SRC = new URL('../src', import.meta.url).pathname

// --- fakes, registered before anything imports the modules that use them -----

interface EnqueuedJob {
  queue: string
  data: Record<string, unknown>
}

const enqueued: EnqueuedJob[] = []

mock.module('bullmq', () => ({
  Queue: class {
    constructor(private readonly queueName: string) {}
    async add(_name: string, data: Record<string, unknown>) {
      enqueued.push({ queue: this.queueName, data })
      return { id: `job-${enqueued.length}` }
    }
    async upsertJobScheduler() {}
    async close() {}
  },
  Worker: class {
    on() {
      return this
    }
    async close() {}
  },
}))

mock.module('ioredis', () => {
  class FakeRedis {
    on() {
      return this
    }
    async quit() {}
    disconnect() {}
  }
  return { default: FakeRedis, Redis: FakeRedis }
})

mock.module(`${SRC}/lib/events.ts`, () => ({
  sessionChannel: (id: string) => `agentoo:session:${id}`,
  controlChannel: (id: string) => `agentoo:control:${id}`,
  publishSessionEvent: async () => {},
  publishControl: async () => {},
  subscribeSession: () => () => {},
  subscribeControl: () => () => {},
}))

mock.module(`${SRC}/features/sessions/runner-options.ts`, () => ({
  optionsFor: async () => ({ cwd: tmpdir() }),
}))

// --- the SDK, for both of its call sites -------------------------------------

/** What the next idea-prompt generation answers with. */
let ideaAnswer: Record<string, unknown> = {
  title: 'Ship the export button',
  prompt: 'Add an export button to the toolbar.',
  assumptions: ['Assumed the button belongs next to Save.'],
}
/** What the next session turn's stream yields. */
let turnStream: Record<string, unknown>[] = []

/** Every prompt string a session turn was actually given, in order. This is
 * the surface (b) is about: the announcement is prepended to the user's own
 * text right before `query()` is called, so what lands here is verbatim what
 * the agent was told. */
const turnPrompts: string[] = []

const USAGE = {
  input_tokens: 10,
  output_tokens: 20,
  cache_creation_input_tokens: 0,
  cache_read_input_tokens: 0,
  cache_creation: null,
  server_tool_use: null,
  service_tier: null,
}

function successResult(text: string): Record<string, unknown> {
  return {
    type: 'result',
    subtype: 'success',
    duration_ms: 1200,
    duration_api_ms: 900,
    is_error: false,
    num_turns: 1,
    result: text,
    stop_reason: 'end_turn',
    total_cost_usd: 0.01,
    usage: USAGE,
    modelUsage: {},
    permission_denials: [],
    uuid: randomUUID(),
    session_id: 'sdk-session-1',
  }
}

/** A `user` message carrying the shape `cancelledWithoutInterrupt` reads —
 * the one stream shape that makes a real turn auto-continue itself. */
function cancelledToolResult(): Record<string, unknown> {
  return {
    type: 'user',
    uuid: randomUUID(),
    session_id: 'sdk-session-1',
    tool_result_meta: [{ non_execution_kind: 'cancelled' }],
    message: { role: 'user', content: [] },
  }
}

mock.module('@anthropic-ai/claude-agent-sdk', () => ({
  query: ({ prompt, options }: { prompt: string; options?: Record<string, unknown> }) => {
    // Only features/ideas/prompt-service.ts sets outputFormat.
    if (options?.outputFormat) {
      const body = JSON.stringify(ideaAnswer)
      return (async function* () {
        yield {
          type: 'system',
          subtype: 'init',
          model: 'claude-test-model',
          session_id: 'sdk-idea-1',
          uuid: randomUUID(),
        }
        yield successResult(body)
      })()
    }
    turnPrompts.push(prompt)
    const stream = turnStream
    return (async function* () {
      for (const message of stream) yield message
    })()
  },
  SYSTEM_PROMPT_DYNAMIC_BOUNDARY: '__SYSTEM_PROMPT_DYNAMIC_BOUNDARY__',
}))

// --- the real modules --------------------------------------------------------

const { and, eq, isNull } = await import('drizzle-orm')
const { closeDb, db } = await import(`${SRC}/db/client.ts`)
const {
  ideaFiles,
  ideaPrompts,
  ideaRuns,
  ideas,
  messages,
  projects,
  sessionFiles,
  sessions,
} = await import(`${SRC}/db/schema.ts`)
const { projectRepo, sessionUploadsDir } = await import(`${SRC}/lib/paths.ts`)
const { continueIdea, handleTurnEnded, sweepIdeaHandoffs } = await import(
  `${SRC}/features/ideas/handoff.ts`
)
const { reconcileOrphanedIdeaRuns } = await import(`${SRC}/features/ideas/run-close.ts`)
const {
  createIdea,
  createIdeaBlock,
  createIdeaComment,
  createIdeaPrompt,
  deleteIdea,
  listIdeaComments,
  moveIdea,
  updateIdea,
} = await import(`${SRC}/features/ideas/service.ts`)
const { attachIdeaAssetsToSession, uploadIdeaFile } = await import(
  `${SRC}/features/ideas/files.ts`
)
const { uploadFile } = await import(`${SRC}/features/attachments/service.ts`)
const { createSession, sendMessage } = await import(`${SRC}/features/sessions/service.ts`)
const { runIdeaPrompt } = await import(`${SRC}/features/ideas/prompt-service.ts`)
const { runTurn } = await import(`${SRC}/queue/session-run.worker.ts`)

const facts: Record<string, unknown> = {}

// --- helpers -----------------------------------------------------------------

async function newProject(name: string): Promise<{ id: string; slug: string }> {
  const slug = `${name}-${randomUUID().slice(0, 8)}`
  const [row] = await db
    .insert(projects)
    .values({ name, slug, source: 'empty', status: 'ready' })
    .returning()
  if (!row) throw new Error('no project row')
  // createSession 400s without it; a plain directory (not a git repo) is
  // enough, and keeps every worktree/branch decision out of these scenarios.
  await mkdir(projectRepo(slug), { recursive: true })
  return { id: row.id, slug }
}

function streamOf(bytes: Uint8Array): ReadableStream<Uint8Array> {
  return new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(bytes)
      controller.close()
    },
  })
}

const textBytes = (s: string) => new TextEncoder().encode(s)
/** Eight bytes of PNG magic — enough for sniff.ts to label it image/png. */
const PNG_MAGIC = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])

/**
 * Drop whatever the previous scenario left queued.
 *
 * Every scenario below drains only the queues it asserts on, so an undrained
 * job outlives its own scenario — and a leftover `turn-ended` job read as the
 * next scenario's first turn ending is exactly the kind of cross-talk that
 * makes a suite pass for the wrong reason. Called at the top of each one.
 */
function resetQueue(): void {
  enqueued.length = 0
}

/** Take (and remove) every queued job for one queue, oldest first. */
function take(queue: string): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = []
  for (let i = enqueued.length - 1; i >= 0; i--) {
    const job = enqueued[i]
    if (job && job.queue === queue) {
      out.unshift(job.data)
      enqueued.splice(i, 1)
    }
  }
  return out
}

/** Run every queued prompt-generation job through the real worker function. */
async function drainPromptJobs(): Promise<number> {
  const jobs = take('idea-prompt')
  for (const job of jobs) await runIdeaPrompt(job.promptId as string)
  return jobs.length
}

/** Run every queued session-run job through the real turn. */
async function drainTurnJobs(): Promise<number> {
  const jobs = take('session-run')
  for (const job of jobs) await runTurn({ sessionId: job.sessionId as string })
  return jobs.length
}

/** Deliver every queued turn-ended job to the real consumer. */
async function drainTurnEnded(): Promise<Record<string, unknown>[]> {
  const jobs = take('turn-ended')
  for (const job of jobs) {
    await handleTurnEnded({
      sessionId: job.sessionId as string,
      promptMessageId: job.promptMessageId as string,
      outcome: job.outcome as string,
    })
  }
  return jobs
}

const ideaRow = async (id: string) =>
  (await db.select().from(ideas).where(eq(ideas.id, id)).limit(1))[0]
const runsForIdea = async (ideaId: string) =>
  db.select().from(ideaRuns).where(eq(ideaRuns.ideaId, ideaId)).orderBy(ideaRuns.startedAt)
const promptsForIdea = async (ideaId: string) =>
  db.select().from(ideaPrompts).where(eq(ideaPrompts.ideaId, ideaId)).orderBy(ideaPrompts.createdAt)
const sessionsForProject = async (projectId: string) =>
  db.select().from(sessions).where(eq(sessions.projectId, projectId))
const sessionFilesFor = async (sessionId: string) =>
  db.select().from(sessionFiles).where(eq(sessionFiles.sessionId, sessionId))
const promptMessagesFor = async (sessionId: string) =>
  db
    .select()
    .from(messages)
    .where(and(eq(messages.sessionId, sessionId), eq(messages.type, 'prompt')))
    .orderBy(messages.seq)

/**
 * Drizzle wraps the driver's own error: its `message` names the SQL it ran and
 * nothing about which constraint rejected it, so a scenario asserting on a
 * constraint name needs the cause appended or it has nothing to match.
 */
function errText(error: unknown): string {
  const head = error instanceof Error ? error.message : String(error)
  const cause = (error as { cause?: unknown } | null)?.cause
  if (cause instanceof Error) return `${head} | ${cause.message}`
  return head
}

async function caught(fn: () => Promise<unknown>): Promise<string> {
  try {
    await fn()
    return ''
  } catch (error) {
    return errText(error)
  }
}

// --- (a) the whole loop, once, for real --------------------------------------

async function fullLoop(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('loop')
  turnPrompts.length = 0

  // 1. The user creates the card, fills its canvas, uploads two assets.
  const created = await createIdea(project, {
    title: 'Export button',
    orchestrator: 'coder',
    maxBudgetUsd: 7,
  })
  const idea = created.id
  const statusOnCreate = created.status

  await createIdeaBlock(idea, {
    kind: 'requirement',
    text: 'Add an export button to the toolbar.',
  })
  await createIdeaBlock(idea, { kind: 'note', text: 'The toolbar lives in the header.' })
  await createIdeaBlock(idea, { kind: 'link', url: 'https://example.com/spec', label: 'the spec' })

  const notesBytes = textBytes('layout: [ Save ][ Export ]\nnothing else changes\n')
  await uploadIdeaFile(idea, 'layout-notes.txt', streamOf(notesBytes), 'text/plain', notesBytes.length)
  const shot = await uploadIdeaFile(idea, 'mock.png', streamOf(PNG_MAGIC), 'image/png', PNG_MAGIC.length)
  await createIdeaBlock(idea, { kind: 'image', assetId: shot.id, caption: 'roughly this' })

  // 2. The user moves it into "selected for development"; the sweep claims it.
  const moved = await moveIdea(idea, { status: 'selected_for_development' })
  const statusOnMove = moved.status

  const claimSweep = await sweepIdeaHandoffs()
  const afterClaim = await ideaRow(idea)
  const promptsAfterClaim = await promptsForIdea(idea)
  const promptJobsQueued = enqueued.filter((j) => j.queue === 'idea-prompt').length

  // The generation worker turns the pending row into a ready one.
  ideaAnswer = {
    title: 'Export button in the toolbar',
    prompt: 'Add an export button beside Save. Read layout-notes.txt and mock.png first.',
    assumptions: ['Assumed the button belongs next to Save.'],
  }
  const promptJobsRun = await drainPromptJobs()
  const promptAfterGeneration = (await promptsForIdea(idea))[0]

  // 3. The next sweep tick dispatches it: session, then assets, then message.
  const dispatchSweep = await sweepIdeaHandoffs()
  const afterDispatch = await ideaRow(idea)
  const sessionId = afterDispatch?.sessionId ?? ''
  const sessionRowsAfterDispatch = await sessionsForProject(project)
  const firstRun = (await runsForIdea(idea))[0]
  const copiedFiles = await sessionFilesFor(sessionId)

  // 4. The agent works, the turn ends cleanly, the turn-ended event closes the
  //    run and the card advances.
  turnStream = [successResult('Added the export button and wired it up.')]
  const turnJobsRun = await drainTurnJobs()
  const turnEndedJobs = await drainTurnEnded()
  const afterFirstTurn = await ideaRow(idea)
  const firstRunClosed = (await runsForIdea(idea))[0]

  // 5. Feedback, then "continue" — into the same session.
  await createIdeaComment(idea, { body: 'Move it to the left of Save, not the right.' })
  await createIdeaComment(idea, { body: 'Also add a keyboard shortcut.' })
  const continueError = await caught(() => continueIdea(idea))
  const commentsAfterContinue = await listIdeaComments(idea)
  const runsAfterContinue = await runsForIdea(idea)

  ideaAnswer = {
    title: 'Export button, on the left',
    prompt: 'Move the export button to the left of Save and add a keyboard shortcut.',
    assumptions: [],
  }
  await drainPromptJobs()
  const followupSweep = await sweepIdeaHandoffs()
  const afterFollowupDispatch = await ideaRow(idea)
  const sessionRowsAfterFollowup = await sessionsForProject(project)
  const followupRun = (await runsForIdea(idea))[1]
  const promptMessages = await promptMessagesFor(sessionId)

  turnStream = [successResult('Moved it left and added ctrl+e.')]
  await drainTurnJobs()
  await drainTurnEnded()
  const afterSecondTurn = await ideaRow(idea)
  const followupRunClosed = (await runsForIdea(idea))[1]

  // 6. The user marks it done.
  const done = await moveIdea(idea, { status: 'done' })

  facts.fullLoop = {
    statusOnCreate,
    statusOnMove,
    claimSweep,
    statusAfterClaim: afterClaim?.status,
    promptCountAfterClaim: promptsAfterClaim.length,
    promptStatusAfterClaim: promptsAfterClaim[0]?.status,
    promptJobsQueued,
    promptJobsRun,
    promptStatusAfterGeneration: promptAfterGeneration?.status,
    promptGeneratedTitle: promptAfterGeneration?.generatedTitle,
    promptAssumptions: promptAfterGeneration?.assumptions,
    promptModel: promptAfterGeneration?.model,
    dispatchSweep,
    statusAfterDispatch: afterDispatch?.status,
    sessionCountAfterDispatch: sessionRowsAfterDispatch.length,
    sessionTitle: sessionRowsAfterDispatch[0]?.title,
    sessionOrchestrator: sessionRowsAfterDispatch[0]?.orchestrator,
    sessionMaxBudgetUsd: sessionRowsAfterDispatch[0]?.maxBudgetUsd,
    firstRunStatus: firstRun?.status,
    firstRunPromptMessageIdSet: Boolean(firstRun?.promptMessageId),
    copiedFilenames: copiedFiles.map((f) => f.originalFilename).sort(),
    turnJobsRun,
    turnEndedOutcomes: turnEndedJobs.map((j) => j.outcome),
    statusAfterFirstTurn: afterFirstTurn?.status,
    firstRunOutcome: firstRunClosed?.outcome,
    firstRunDetail: firstRunClosed?.detail,
    lastErrorAfterFirstTurn: afterFirstTurn?.lastError,
    continueError,
    commentsConsumed: commentsAfterContinue.filter((c) => c.consumedAt !== null).length,
    commentCount: commentsAfterContinue.length,
    runCountAfterContinue: runsAfterContinue.length,
    followupRunKind: runsAfterContinue.find((r) => r.endedAt === null)?.kind,
    followupSweep,
    statusAfterFollowupDispatch: afterFollowupDispatch?.status,
    // The load-bearing one for step 5: the follow-up must reuse the session
    // the initial handoff created, not create a second one.
    sessionCountAfterFollowup: sessionRowsAfterFollowup.length,
    sessionIdUnchanged: afterFollowupDispatch?.sessionId === sessionId,
    followupRunSessionIsSame: followupRun?.sessionId === sessionId,
    promptMessageTexts: promptMessages.map((m) => (m.payload as { text?: string }).text ?? ''),
    statusAfterSecondTurn: afterSecondTurn?.status,
    followupRunOutcome: followupRunClosed?.outcome,
    statusAfterDone: done.status,
    // Both runs closed, nothing left open on the card.
    openRunsAtEnd: (await runsForIdea(idea)).filter((r) => r.endedAt === null).length,
    runCountAtEnd: (await runsForIdea(idea)).length,
  }

  // (b) rides on this same loop: what the agent was actually told.
  facts.announcement = {
    turnPromptCount: turnPrompts.length,
    firstTurnPrompt: turnPrompts[0] ?? '',
    secondTurnPrompt: turnPrompts[1] ?? '',
    uploadsDir: sessionUploadsDir(sessionId),
    copiedStoredNames: copiedFiles.map((f) => f.storedName).sort(),
    // Re-read: `announcedSeq` is null on the rows the handoff just inserted
    // and is stamped by the turn's own claim transaction, so this has to be
    // read after a turn has run, not from the rows captured at dispatch.
    announcedSeqs: (await sessionFilesFor(sessionId)).map((f) => f.announcedSeq).sort(),
  }
}

/**
 * The control for (b), and the reason the ordering in `dispatchRun` is
 * load-bearing rather than tidy.
 *
 * Same fixture as the handoff above with exactly one thing changed: the asset
 * is copied into the session only *after* the prompt's turn has already been
 * claimed. The announcement is computed inside that claim's own transaction
 * (queue/session-run.worker.ts's `toAnnounce` select), so the agent runs the
 * whole first turn never having been told the file exists, and only hears
 * about it on the turn after. This is what a `session_files` row landing after
 * the prompt actually costs — asserted as a fact, so the "before" case above
 * is a claim about behaviour rather than about a call order.
 */
async function assetAfterPromptIsAnnouncedLate(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('late')
  const idea = (await createIdea(project, { title: 'Late', orchestrator: 'coder' })).id
  const bytes = textBytes('the asset the agent should have had\n')
  await uploadIdeaFile(idea, 'late.txt', streamOf(bytes), 'text/plain', bytes.length)

  const session = await createSession(project, { title: 'late session', orchestrator: 'coder' })

  turnPrompts.length = 0
  // The prompt goes first, and its turn is claimed before the copy lands.
  await sendMessage(session.id, 'Read late.txt and get on with it.')
  turnStream = [successResult('nothing to read')]
  await drainTurnJobs()

  // The copy the handoff was supposed to have done first.
  await attachIdeaAssetsToSession(idea, session.id)

  // The next turn is the first one that ever mentions the file.
  await sendMessage(session.id, 'anything at all')
  turnStream = [successResult('found it, a turn late')]
  await drainTurnJobs()

  facts.announcedLate = {
    firstTurnPrompt: turnPrompts[0] ?? '',
    secondTurnPrompt: turnPrompts[1] ?? '',
  }
}

// --- (c) idempotency across the seams ----------------------------------------

async function idempotency(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('idem')
  const idea = (await createIdea(project, { title: 'Idem', orchestrator: 'coder' })).id

  const aBytes = textBytes('alpha asset\n')
  const bBytes = textBytes('bravo asset\n')
  await uploadIdeaFile(idea, 'alpha.txt', streamOf(aBytes), 'text/plain', aBytes.length)
  await uploadIdeaFile(idea, 'bravo.txt', streamOf(bBytes), 'text/plain', bBytes.length)

  // Identical bytes, a different name: uploadIdeaFile's own checksum dedup.
  const reUpload = await uploadIdeaFile(
    idea,
    'alpha-copy.txt',
    streamOf(aBytes),
    'text/plain',
    aBytes.length,
  )
  const ideaFileRows = await db
    .select()
    .from(ideaFiles)
    .where(and(eq(ideaFiles.ideaId, idea), isNull(ideaFiles.deletedAt)))

  // And the constraint behind that dedup, stated directly: a second live row
  // with the same checksum on one idea is not merely avoided by the service,
  // it is impossible.
  const duplicateRowError = await caught(async () => {
    const source = ideaFileRows[0]
    if (!source) throw new Error('no idea file row to duplicate')
    await db.insert(ideaFiles).values({
      ideaId: idea,
      originalFilename: 'alpha-again.txt',
      storedName: `${randomUUID()}-alpha-again.txt`,
      mimeType: 'text/plain',
      sizeBytes: source.sizeBytes,
      checksum: source.checksum,
    })
  })

  const session = await createSession(project, { title: 'idem session', orchestrator: 'coder' })

  await attachIdeaAssetsToSession(idea, session.id)
  const afterFirstAttach = await sessionFilesFor(session.id)

  // The continue path: the same (ideaId, sessionId) pair handed off again.
  await attachIdeaAssetsToSession(idea, session.id)
  const afterSecondAttach = await sessionFilesFor(session.id)

  // A genuine concurrent double-handoff — which needs a session nothing has
  // attached to yet. Run against `session` above, both calls would find every
  // checksum already present and return before copying a byte, so the
  // onConflictDoNothing this is meant to exercise would never be reached and
  // the assertion would pass without having tested anything.
  const raced = await createSession(project, { title: 'raced session', orchestrator: 'coder' })
  await Promise.all([
    attachIdeaAssetsToSession(idea, raced.id),
    attachIdeaAssetsToSession(idea, raced.id),
  ])
  const afterConcurrentAttach = await sessionFilesFor(raced.id)
  const blobsOnDisk = (await readdir(sessionUploadsDir(raced.id))).filter(
    (name) => !name.startsWith('.'),
  )
  // The invariant the docblock actually promises: a lost race may leave an
  // unrowed blob (which ATTACHMENTS_GC_GRACE_MS reaps), never a row with no
  // blob behind it.
  const rowsWithMissingBlob = afterConcurrentAttach.filter(
    (row) => !blobsOnDisk.includes(row.storedName),
  ).length

  facts.idempotency = {
    reUploadReturnedExistingName: reUpload.originalFilename,
    ideaFileRowCount: ideaFileRows.length,
    duplicateRowError,
    firstAttachCount: afterFirstAttach.length,
    secondAttachCount: afterSecondAttach.length,
    concurrentAttachCount: afterConcurrentAttach.length,
    attachedNames: afterConcurrentAttach.map((f) => f.originalFilename).sort(),
    rowsWithMissingBlob,
    // Recorded, not asserted to an exact number: which of the two concurrent
    // copies wins each insert is genuinely nondeterministic, so the count of
    // leftover blobs is too. `rowsWithMissingBlob` above is the deterministic
    // half, and is what the assertion uses.
    blobCountOnDisk: blobsOnDisk.length,
  }
}

/**
 * An idea asset whose bytes already exist in the session under a different
 * name — the third case (c) asks about. The dedup index is keyed on
 * (session_id, checksum), so the idea's own filename never lands, while the
 * generated prompt still names it. Driven all the way through a real turn so
 * the consequence is what gets recorded, not the intent.
 */
async function checksumCollisionWithSessionUpload(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('collide')
  const idea = (await createIdea(project, { title: 'Collide', orchestrator: 'coder' })).id

  const shared = textBytes('the very same bytes\n')
  await uploadIdeaFile(idea, 'diagram.txt', streamOf(shared), 'text/plain', shared.length)

  const session = await createSession(project, { title: 'collide session', orchestrator: 'coder' })
  await uploadFile(session.id, 'screenshot.txt', streamOf(shared), 'text/plain', shared.length)

  await attachIdeaAssetsToSession(idea, session.id)
  const files = await sessionFilesFor(session.id)

  turnPrompts.length = 0
  turnStream = [successResult('done')]
  await sendMessage(session.id, 'Read diagram.txt before you start.')
  await drainTurnJobs()

  facts.checksumCollision = {
    sessionFileCount: files.length,
    sessionFilenames: files.map((f) => f.originalFilename),
    turnPrompt: turnPrompts[0] ?? '',
  }
}

/**
 * An asset added to the card *after* its first run, then handed off by the
 * continue path — the same ordering constraint (b) is about, on the seam
 * nothing had driven: the second dispatch's `attachIdeaAssetsToSession` runs
 * against a session that already holds an already-announced file, and the new
 * asset still has to land before the follow-up prompt message so that turn's
 * own announcement names it.
 */
async function followupAssetAnnouncement(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('newasset')
  const idea = (await createIdea(project, { title: 'New asset', orchestrator: 'coder' })).id

  const firstBytes = textBytes('the first asset\n')
  await uploadIdeaFile(idea, 'first.txt', streamOf(firstBytes), 'text/plain', firstBytes.length)

  await moveIdea(idea, { status: 'selected_for_development' })
  await sweepIdeaHandoffs()
  ideaAnswer = {
    title: 'First pass',
    prompt: 'Read first.txt and do the first pass.',
    assumptions: [],
  }
  await drainPromptJobs()
  await sweepIdeaHandoffs()
  const sessionId = (await ideaRow(idea))?.sessionId ?? ''
  if (!sessionId) throw new Error('followupAssetAnnouncement: the handoff created no session')

  turnPrompts.length = 0
  turnStream = [successResult('first pass done')]
  await drainTurnJobs()
  await drainTurnEnded()
  const statusAfterFirstRun = (await ideaRow(idea))?.status

  // The user adds a second asset, then clicks continue.
  const secondBytes = textBytes('the second asset, added after the first run\n')
  await uploadIdeaFile(idea, 'second.txt', streamOf(secondBytes), 'text/plain', secondBytes.length)
  await continueIdea(idea)
  ideaAnswer = { title: 'Second pass', prompt: 'Now read second.txt and finish.', assumptions: [] }
  await drainPromptJobs()
  await sweepIdeaHandoffs()

  turnStream = [successResult('second pass done')]
  await drainTurnJobs()
  await drainTurnEnded()

  const files = await sessionFilesFor(sessionId)
  const prompts = await promptMessagesFor(sessionId)

  facts.followupAsset = {
    statusAfterFirstRun,
    statusAtEnd: (await ideaRow(idea))?.status,
    sessionFilenames: files.map((f) => f.originalFilename).sort(),
    firstTurnPrompt: turnPrompts[0] ?? '',
    secondTurnPrompt: turnPrompts[1] ?? '',
    promptSeqs: prompts.map((m) => m.seq),
    announcedBy: files
      .map((f) => ({ name: f.originalFilename, seq: f.announcedSeq }))
      .sort((a, b) => a.name.localeCompare(b.name)),
  }
}

// --- (d) the continuation chain ----------------------------------------------

/** The initial handoff, driven to `running`, for a scenario that only cares
 * about what happens after that. */
async function handOffToRunning(
  name: string,
  answer: Record<string, unknown>,
): Promise<{ project: string; idea: string; sessionId: string; runId: string }> {
  resetQueue()
  const { id: project } = await newProject(name)
  const idea = (await createIdea(project, { title: name, orchestrator: 'coder' })).id
  await moveIdea(idea, { status: 'selected_for_development' })
  await sweepIdeaHandoffs()
  ideaAnswer = answer
  await drainPromptJobs()
  await sweepIdeaHandoffs()
  const row = await ideaRow(idea)
  const run = (await runsForIdea(idea))[0]
  if (!row?.sessionId || !run) throw new Error(`${name}: handoff did not reach running`)
  return { project, idea, sessionId: row.sessionId, runId: run.id }
}

async function realContinuationChain(): Promise<void> {
  const { idea, sessionId } = await handOffToRunning('chain', {
    title: 'Chain',
    prompt: 'Do the long thing.',
    assumptions: [],
  })

  const steps: Record<string, unknown>[] = []

  // Two turns that each end with a harness-cancelled tool call — the one
  // stream shape session-run.worker.ts auto-continues over. Each one is the
  // *same* run continuing, so the card must not move.
  for (let i = 0; i < 2; i++) {
    turnStream = [cancelledToolResult(), successResult(`partial ${i}`)]
    await drainTurnJobs()
    const jobs = await drainTurnEnded()
    const run = (await runsForIdea(idea))[0]
    const row = await ideaRow(idea)
    steps.push({
      outcomes: jobs.map((j) => j.outcome),
      runOpen: run?.endedAt === null,
      runStatus: run?.status,
      ideaStatus: row?.status,
    })
  }

  // The third turn finishes for real, several hops down the chain from the
  // prompt the run recorded.
  turnStream = [successResult('All of it is done.')]
  await drainTurnJobs()
  const finalJobs = await drainTurnEnded()
  const finalRun = (await runsForIdea(idea))[0]
  const finalIdea = await ideaRow(idea)

  const chain = await promptMessagesFor(sessionId)

  facts.realChain = {
    steps,
    finalOutcomes: finalJobs.map((j) => j.outcome),
    finalRunOutcome: finalRun?.outcome,
    finalRunStatus: finalRun?.status,
    finalIdeaStatus: finalIdea?.status,
    finalRunDetail: finalRun?.detail,
    chainLength: chain.length,
    // The chain reconstructed from the transcript alone: every continuation
    // links back to the prompt whose turn spawned it.
    chainLinks: chain.map((m) => ({
      auto: (m.payload as { auto?: unknown }).auto === true,
      continues: m.continuesMessageId === null ? null : chain.findIndex((c) => c.id === m.continuesMessageId),
      outcome: m.turnOutcome,
    })),
    rootIsRunRoot: chain[0]?.id === (await runsForIdea(idea))[0]?.promptMessageId,
  }
}

/**
 * A chain longer than MAX_AUTO_CONTINUATIONS (3), which is reachable in
 * production because an operator message mid-chain resets that budget — see
 * `messageIsInChain`'s own docblock. Built directly rather than driven, since
 * driving it would mean interleaving operator sends the scenario above already
 * covers separately; what is under test here is only that the walk has no
 * hidden bound of four.
 */
async function longSyntheticChain(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('long-chain')
  const idea = (await createIdea(project, { title: 'Long', orchestrator: 'coder' })).id
  await db.update(ideas).set({ status: 'in_progress_dev' }).where(eq(ideas.id, idea))
  const session = await createSession(project, { title: 'long', orchestrator: 'coder' })

  const HOPS = 7
  const ids: string[] = []
  for (let seq = 0; seq < HOPS + 1; seq++) {
    const [row] = await db
      .insert(messages)
      .values({
        sessionId: session.id,
        seq,
        type: 'prompt',
        payload: { text: `hop ${seq}`, ...(seq > 0 && { auto: true }) },
        ...(seq > 0 && { continuesMessageId: ids[seq - 1] }),
      })
      .returning()
    if (!row) throw new Error('no message row')
    ids.push(row.id)
  }
  const root = ids[0]
  if (!root) throw new Error('no root message')

  const [run] = await db
    .insert(ideaRuns)
    .values({
      ideaId: idea,
      sessionId: session.id,
      promptMessageId: root,
      kind: 'initial',
      status: 'running',
    })
    .returning()
  if (!run) throw new Error('no run row')

  const openThroughChain: boolean[] = []
  const statusThroughChain: string[] = []
  for (let hop = 0; hop < HOPS; hop++) {
    const id = ids[hop]
    if (!id) throw new Error('missing hop')
    await handleTurnEnded({ sessionId: session.id, promptMessageId: id, outcome: 'continuing' })
    const [r] = await db.select().from(ideaRuns).where(eq(ideaRuns.id, run.id)).limit(1)
    openThroughChain.push(r?.endedAt === null)
    statusThroughChain.push((await ideaRow(idea))?.status ?? '')
  }

  // The seventh hop's own turn finishes — four hops past the auto-continuation
  // budget.
  const tail = ids[HOPS]
  if (!tail) throw new Error('missing tail')
  await db
    .update(messages)
    .set({ type: 'result', payload: { type: 'result', subtype: 'success', result: 'Finished on hop 7.' } })
    .where(eq(messages.id, tail))
  await handleTurnEnded({ sessionId: session.id, promptMessageId: tail, outcome: 'completed' })
  const [closed] = await db.select().from(ideaRuns).where(eq(ideaRuns.id, run.id)).limit(1)

  // And an operator message that is *not* in this run's chain, on the same
  // session, ending cleanly: it must not close a run it has nothing to do with.
  const { id: project2 } = await newProject('offchain')
  const idea2 = (await createIdea(project2, { title: 'Offchain', orchestrator: 'coder' })).id
  await db.update(ideas).set({ status: 'in_progress_dev' }).where(eq(ideas.id, idea2))
  const session2 = await createSession(project2, { title: 'offchain', orchestrator: 'coder' })
  const [rootRow] = await db
    .insert(messages)
    .values({ sessionId: session2.id, seq: 0, type: 'prompt', payload: { text: 'the handoff' } })
    .returning()
  const [strayRow] = await db
    .insert(messages)
    .values({ sessionId: session2.id, seq: 1, type: 'prompt', payload: { text: 'something else' } })
    .returning()
  if (!rootRow || !strayRow) throw new Error('no message rows')
  const [run2] = await db
    .insert(ideaRuns)
    .values({
      ideaId: idea2,
      sessionId: session2.id,
      promptMessageId: rootRow.id,
      kind: 'initial',
      status: 'running',
    })
    .returning()
  if (!run2) throw new Error('no run row')
  await handleTurnEnded({
    sessionId: session2.id,
    promptMessageId: strayRow.id,
    outcome: 'completed',
  })
  const [run2After] = await db.select().from(ideaRuns).where(eq(ideaRuns.id, run2.id)).limit(1)

  facts.longChain = {
    hops: HOPS,
    openThroughChain,
    statusThroughChain,
    closedOutcome: closed?.outcome,
    closedStatus: closed?.status,
    closedDetail: closed?.detail,
    ideaStatusAfterTail: (await ideaRow(idea))?.status,
    offChainRunStillOpen: run2After?.endedAt === null,
    offChainIdeaStatus: (await ideaRow(idea2))?.status,
  }
}

// --- (e) the failure injection: a card stranded at the claim seam ------------
//
// Chosen over the failure modes dispatchRun already handles because those all
// end in `closeRun(needs_attention)` — a card that stops, says why on
// `ideas.lastError`, and re-triggers once the user acts (idea-handoff.test.ts's
// retry-gate scenarios prove that). This one has no such ending.
// `claimIdeaForHandoff` writes the open run first and links `promptId` second
// (features/ideas/handoff.ts:89-102). A worker killed between those two writes
// leaves an open run with a null `promptId`, and `progressOpenRuns` skips
// exactly that row every tick (`if (!run.promptId) continue`, line 341) while
// the open run makes `claimSelectedIdeas` skip the card too. Nothing in the
// codebase closes it: `reconcileOrphanedIdeaRuns` only looks at `running`
// rows, and there is no HTTP route that closes a run. A silently stuck card is
// the failure mode this whole feature was designed against, so that is the
// seam worth injecting at.

async function strandedAtClaimSeam(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('strand-claim')
  const idea = (await createIdea(project, { title: 'Strand', orchestrator: 'coder' })).id
  await moveIdea(idea, { status: 'selected_for_development' })

  // Exactly claimIdeaForHandoff's first write, and nothing after it.
  const [run] = await db
    .insert(ideaRuns)
    .values({ ideaId: idea, kind: 'initial', status: 'generating' })
    .returning()
  if (!run) throw new Error('no run row')

  const sweeps: { claimed: number; dispatched: number; failed: number }[] = []
  for (let i = 0; i < 3; i++) sweeps.push(await sweepIdeaHandoffs())

  // Every operator remedy the feature documents, tried in turn.
  const orphanReconciled = await reconcileOrphanedIdeaRuns()
  const deleteError = await caught(() => deleteIdea(idea))
  const continueError = await caught(() => continueIdea(idea))
  await updateIdea(idea, { orchestrator: 'coder' }) // bumps ideas.updatedAt
  const sweepAfterRemedy = await sweepIdeaHandoffs()
  const reMoveError = await caught(() => moveIdea(idea, { status: 'selected_for_development' }))
  const sweepAfterReMove = await sweepIdeaHandoffs()

  const [runAfter] = await db.select().from(ideaRuns).where(eq(ideaRuns.id, run.id)).limit(1)
  const ideaAfter = await ideaRow(idea)

  facts.strandedAtClaim = {
    sweeps,
    orphanReconciled,
    deleteError,
    continueError,
    sweepAfterRemedy,
    reMoveError,
    sweepAfterReMove,
    runStatus: runAfter?.status,
    runOpen: runAfter?.endedAt === null,
    runPromptIdNull: runAfter?.promptId === null,
    ideaStatus: ideaAfter?.status,
    ideaLastError: ideaAfter?.lastError,
    promptCount: (await promptsForIdea(idea)).length,
    sessionCount: (await sessionsForProject(project)).length,
  }
}

/**
 * The same strand reached the other way, through the gap
 * features/ideas/prompt-service.ts documents in writing: `attempts: 1` and a
 * worker killed mid-generation leave `idea_prompts` `pending` forever. That
 * file names the intended remedy — "a regenerate action on the HTTP surface"
 * — and `POST /ideas/{id}/prompts` is it. This applies that remedy and records
 * whether it actually unsticks the card.
 */
async function strandedOnPendingPrompt(): Promise<void> {
  resetQueue()
  const { id: project } = await newProject('strand-pending')
  const idea = (await createIdea(project, { title: 'Pending', orchestrator: 'coder' })).id
  await moveIdea(idea, { status: 'selected_for_development' })

  await sweepIdeaHandoffs() // claims, inserts the pending prompt, links promptId
  const stalePrompt = (await promptsForIdea(idea))[0]
  take('idea-prompt') // the generation worker was killed: the job never runs

  const sweepWithPendingPrompt = await sweepIdeaHandoffs()
  const runWhilePending = (await runsForIdea(idea))[0]

  // The documented remedy: repost the same kind. It supersedes the stale row.
  ideaAnswer = { title: 'Regenerated', prompt: 'Do the thing.', assumptions: [] }
  const regenerated = await createIdeaPrompt(idea, { kind: 'initial' })
  await drainPromptJobs()

  const sweepAfterRegenerate = await sweepIdeaHandoffs()
  const promptsAfter = await promptsForIdea(idea)
  const runAfter = (await runsForIdea(idea))[0]
  const ideaAfter = await ideaRow(idea)

  facts.strandedOnPendingPrompt = {
    stalePromptStatus: stalePrompt?.status,
    runPromptIdIsStale: runAfter?.promptId === stalePrompt?.id,
    sweepWithPendingPrompt,
    runStatusWhilePending: runWhilePending?.status,
    sweepAfterRegenerate,
    promptStatuses: promptsAfter.map((p) => p.status),
    regeneratedIsReady:
      promptsAfter.find((p) => p.id === regenerated.id)?.status === 'ready',
    runStatusAfter: runAfter?.status,
    runOpenAfter: runAfter?.endedAt === null,
    ideaStatusAfter: ideaAfter?.status,
    ideaLastErrorAfter: ideaAfter?.lastError,
    sessionCount: (await sessionsForProject(project)).length,
  }
}

// --- main --------------------------------------------------------------------

async function main() {
  await fullLoop()
  await assetAfterPromptIsAnnouncedLate()
  await idempotency()
  await checksumCollisionWithSessionUpload()
  await followupAssetAnnouncement()
  await realContinuationChain()
  await longSyntheticChain()
  await strandedAtClaimSeam()
  await strandedOnPendingPrompt()

  console.log(`__FACTS__${JSON.stringify(facts)}`)
}

main()
  .then(async () => {
    await closeDb()
    process.exit(0)
  })
  .catch(async (error) => {
    const detail = error instanceof Error ? (error.stack ?? error.message) : String(error)
    // Drizzle wraps the driver's error: without the cause, "Failed query"
    // names the SQL and hides the constraint or column that actually broke.
    const cause = (error as { cause?: unknown }).cause
    const causeDetail =
      cause instanceof Error ? `\ncause: ${cause.message}` : cause ? `\ncause: ${String(cause)}` : ''
    console.log(`__ERROR__${detail}${causeDetail}`)
    await closeDb().catch(() => {})
    process.exit(1)
  })
