/**
 * The schedule builder's own cron ⇄ preset conversion, and nothing else —
 * deliberately free of React and i18next (aside from `describeSchedule`'s
 * translate-function parameter) so the round-trip rules can be unit tested
 * as plain functions, the same reasoning `shared/store/tabs.ts` gives for
 * staying free of the router.
 *
 * A "preset" is the schedule builder's own in-memory shape — what a reader
 * picks from the kind selector, plus whatever that kind needs (a time, a set
 * of days, an hour step). `toCron` renders one to the 5-field string the API
 * stores; `fromCron` reads a stored string back into a preset, so editing an
 * existing automation reopens the same picker it was created from rather
 * than always landing on "Custom".
 *
 * The five canonical forms `toCron` ever produces — and the only shapes
 * `fromCron` recognises as anything other than `'custom'`:
 *
 *   - Every day at HH:MM         → `M H * * *`
 *   - Weekdays (Mon–Fri) at HH:MM → `M H * * 1-5`
 *   - Weekends (Sat, Sun) at HH:MM → `M H * * 0,6`
 *   - Specific days at HH:MM     → `M H * * d1,d2,…` (ascending, 0=Sun…6=Sat)
 *   - Every N hours at :MM       → `M * * * *` (N=1) or `M *​/N * * *` (N>1)
 *
 * `M`/`H`/`N` are always plain integers with no leading zero — `9`, never
 * `09` — matching how every cron library (and the backend's own parser)
 * reads a 5-field expression; the leading-zero form is only ever a display
 * concern (an `<input type="time">` needs `09:00`), handled by `timeToParts`/
 * `partsToTime` below, never by this module's cron text itself.
 */

export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6

/** The `<select>` this module's "every N hours" preset offers — the brief's
 *  own "N = 1..12 at least" floor, not a hard ceiling `fromCron` enforces:
 *  see its own comment below on why a cron outside this list still parses
 *  back rather than being demoted to 'custom'. */
export const EVERY_N_HOURS_OPTIONS = [1, 2, 3, 4, 6, 8, 12] as const

export type SchedulePreset =
  | { kind: 'daily'; time: string }
  | { kind: 'weekdays'; time: string }
  | { kind: 'weekends'; time: string }
  | { kind: 'days'; time: string; days: DayOfWeek[] }
  | { kind: 'hourly'; everyHours: number; minute: number }
  | { kind: 'custom'; cron: string }

export type ScheduleKind = SchedulePreset['kind']

/** `"09:05"` → `{ hour: 9, minute: 5 }` — the `<input type="time">` shape
 *  parsed down to the plain integers cron fields are made of. Never fails
 *  silently: a caller only ever has this fed from a time input's own value,
 *  which is always well-formed. */
function timeToParts(time: string): { hour: number; minute: number } {
  const [h, m] = time.split(':')
  return { hour: Number(h), minute: Number(m) }
}

/** The reverse of `timeToParts`, re-padded for the `<input type="time">`
 *  this feeds — cron's own `9` becomes the input's required `09`. */
function partsToTime(hour: number, minute: number): string {
  return `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`
}

function sortedUnique(days: DayOfWeek[]): DayOfWeek[] {
  return [...new Set(days)].sort((a, b) => a - b)
}

const WEEKDAYS: DayOfWeek[] = [1, 2, 3, 4, 5]
const WEEKENDS: DayOfWeek[] = [0, 6]

const sameDays = (a: DayOfWeek[], b: DayOfWeek[]) =>
  a.length === b.length && a.every((d, i) => d === b[i])

/** A preset → the 5-field cron string the API stores. */
export function toCron(preset: SchedulePreset): string {
  switch (preset.kind) {
    case 'daily': {
      const { hour, minute } = timeToParts(preset.time)
      return `${minute} ${hour} * * *`
    }
    case 'weekdays': {
      const { hour, minute } = timeToParts(preset.time)
      return `${minute} ${hour} * * 1-5`
    }
    case 'weekends': {
      const { hour, minute } = timeToParts(preset.time)
      return `${minute} ${hour} * * 0,6`
    }
    case 'days': {
      const { hour, minute } = timeToParts(preset.time)
      return `${minute} ${hour} * * ${sortedUnique(preset.days).join(',')}`
    }
    case 'hourly':
      return preset.everyHours <= 1
        ? `${preset.minute} * * * *`
        : `${preset.minute} */${preset.everyHours} * * *`
    case 'custom':
      return preset.cron
  }
}

/** A plain integer field, no leading zero — exactly what `toCron` ever
 *  writes into the minute/hour fields, and the only shape `fromCron` accepts
 *  there: anything else (a leading zero, a range, a step) means this cron
 *  was not generated by one of the five canonical forms above. */
const PLAIN_INT = /^(0|[1-9]\d*)$/

function parsePlainInt(field: string, max: number): number | null {
  if (!PLAIN_INT.test(field)) return null
  const n = Number(field)
  return n <= max ? n : null
}

/** The day-of-week field, read as either the canonical weekday/weekend
 *  shorthand or a plain ascending comma list (a single day, with no comma
 *  at all, is the one-element case of that same list, and is accepted) —
 *  see the module comment for which written form is canonical for which
 *  case. Returns `null` for anything else (a step, named days, a range
 *  other than `1-5`, or a non-ascending or duplicated list), which sends
 *  the whole cron to `'custom'`. */
function parseDayField(field: string): DayOfWeek[] | null {
  if (field === '1-5') return WEEKDAYS
  if (field === '0,6') return WEEKENDS
  if (!/^\d(,\d)*$/.test(field)) return null
  const days = field.split(',').map(Number)
  let previous = -1
  for (const day of days) {
    if (day > 6) return null
    if (day <= previous) return null // strictly ascending, no dupes
    previous = day
  }
  return days as DayOfWeek[]
}

/**
 * The 5-field cron string → the preset that produced it, or `'custom'` (the
 * raw string kept verbatim) for anything that isn't one of this module's own
 * canonical forms — a hand-written cron the reader typed, or one from before
 * this feature existed, reopens as "Custom" rather than a guess.
 */
export function fromCron(cron: string): SchedulePreset {
  const trimmed = cron.trim()
  const fields = trimmed.split(/\s+/)
  if (fields.length !== 5) return { kind: 'custom', cron: trimmed }

  const [minuteField, hourField, dom, month, dowField] = fields as [
    string,
    string,
    string,
    string,
    string,
  ]
  // Every canonical form here only ever varies minute/hour/day-of-week —
  // anything touching day-of-month or month is unconditionally custom.
  if (dom !== '*' || month !== '*') return { kind: 'custom', cron: trimmed }

  const minute = parsePlainInt(minuteField, 59)
  if (minute === null) return { kind: 'custom', cron: trimmed }

  // `* * * * *` / `M *​/N * * *`: every hour, or every Nth hour from
  // midnight — only recognised with day-of-week also wide open.
  if (dowField === '*') {
    if (hourField === '*') return { kind: 'hourly', everyHours: 1, minute }
    const everyMatch = /^\*\/([2-9]|1[0-2])$/.exec(hourField)
    if (everyMatch) return { kind: 'hourly', everyHours: Number(everyMatch[1]), minute }
    // Any other hour field under a wide-open day-of-week falls through: a
    // plain hour (0–23) is handled by the daily case below, anything else
    // reaches `parsePlainInt` there and comes back `null` → custom.
  }

  const hour = parsePlainInt(hourField, 23)
  if (hour === null) return { kind: 'custom', cron: trimmed }

  if (dowField === '*') return { kind: 'daily', time: partsToTime(hour, minute) }

  const days = parseDayField(dowField)
  if (days === null) return { kind: 'custom', cron: trimmed }
  const time = partsToTime(hour, minute)
  if (sameDays(days, WEEKDAYS)) return { kind: 'weekdays', time }
  if (sameDays(days, WEEKENDS)) return { kind: 'weekends', time }
  return { kind: 'days', time, days }
}

/** Minimal shape of `useTranslation()`'s `t` this module needs — avoiding a
 *  direct `i18next`/`react-i18next` dependency keeps this file importable
 *  from a plain `bun test` with no provider mounted, the same reason
 *  `toCron`/`fromCron` above take and return plain data rather than JSX. */
type Translate = (key: string, options?: Record<string, unknown>) => string

const DAY_KEYS = [
  'automations.schedule.day.sun',
  'automations.schedule.day.mon',
  'automations.schedule.day.tue',
  'automations.schedule.day.wed',
  'automations.schedule.day.thu',
  'automations.schedule.day.fri',
  'automations.schedule.day.sat',
] as const

/**
 * The one-line human summary the list and detail pages show — "Every day at
 * 09:00", "Weekdays at 09:00", "Every 3 hours at :15" — falling back to
 * "Custom: <cron>" for anything `fromCron` didn't recognise. Reuses
 * `fromCron` rather than re-deriving the shape from the raw string, so the
 * two can never disagree about which cron reads as which kind.
 */
export function describeSchedule(cron: string, t: Translate): string {
  const preset = fromCron(cron)
  switch (preset.kind) {
    case 'daily':
      return t('automations.schedule.describe.daily', { time: preset.time })
    case 'weekdays':
      return t('automations.schedule.describe.weekdays', { time: preset.time })
    case 'weekends':
      return t('automations.schedule.describe.weekends', { time: preset.time })
    case 'days':
      return t('automations.schedule.describe.days', {
        time: preset.time,
        days: preset.days.map((d) => t(DAY_KEYS[d])).join(', '),
      })
    case 'hourly': {
      // Padded to two digits — a clock minute, like the daily form's own
      // "09:00" — so ":5" (which reads as a different time, five minutes
      // past the hour read as "five") never reaches the reader.
      const minute = String(preset.minute).padStart(2, '0')
      return preset.everyHours <= 1
        ? t('automations.schedule.describe.everyHour', { minute })
        : t('automations.schedule.describe.everyNHours', { n: preset.everyHours, minute })
    }
    case 'custom':
      return t('automations.schedule.describe.custom', { cron: preset.cron })
  }
}

/**
 * The schedule builder's own field shape — one flat object covering every
 * preset's fields at once (`time` for daily/weekdays/weekends/days,
 * `everyHours`/`minute` for hourly, `customCron` for custom), rather than the
 * `SchedulePreset` union — the same reason `idea-canvas.tsx`'s `BlockDialog`
 * keeps one flat `values` record across its own kind switch instead of a
 * union: a reader flipping the kind selector back and forth should not lose
 * whatever they already typed into a field the current kind doesn't use.
 */
export interface ScheduleFieldsValue {
  scheduleKind: ScheduleKind
  time: string
  days: DayOfWeek[]
  everyHours: number
  minute: number
  customCron: string
}

/** A fresh automation's starting point: once a day, at 09:00. */
export const DEFAULT_SCHEDULE_FIELDS: ScheduleFieldsValue = {
  scheduleKind: 'daily',
  time: '09:00',
  days: [],
  everyHours: 1,
  minute: 0,
  customCron: '',
}

/** The builder's own fields → the preset `toCron`/`describeSchedule` take —
 *  picks out of the flat `ScheduleFieldsValue` only the fields the current
 *  `scheduleKind` actually uses. */
export function presetFromFields(fields: ScheduleFieldsValue): SchedulePreset {
  switch (fields.scheduleKind) {
    case 'daily':
      return { kind: 'daily', time: fields.time }
    case 'weekdays':
      return { kind: 'weekdays', time: fields.time }
    case 'weekends':
      return { kind: 'weekends', time: fields.time }
    case 'days':
      return { kind: 'days', time: fields.time, days: fields.days }
    case 'hourly':
      return { kind: 'hourly', everyHours: fields.everyHours, minute: fields.minute }
    case 'custom':
      return { kind: 'custom', cron: fields.customCron }
  }
}

/** The reverse of `presetFromFields` — reopening an existing automation's
 *  cron in the builder. Fields the parsed preset doesn't use keep
 *  `DEFAULT_SCHEDULE_FIELDS`' own values, so switching the kind selector
 *  away and back doesn't show a stale leftover from a *different* cron. */
export function fieldsFromPreset(preset: SchedulePreset): ScheduleFieldsValue {
  switch (preset.kind) {
    case 'daily':
    case 'weekdays':
    case 'weekends':
      return { ...DEFAULT_SCHEDULE_FIELDS, scheduleKind: preset.kind, time: preset.time }
    case 'days':
      return {
        ...DEFAULT_SCHEDULE_FIELDS,
        scheduleKind: 'days',
        time: preset.time,
        days: preset.days,
      }
    case 'hourly':
      return {
        ...DEFAULT_SCHEDULE_FIELDS,
        scheduleKind: 'hourly',
        everyHours: preset.everyHours,
        minute: preset.minute,
      }
    case 'custom':
      return { ...DEFAULT_SCHEDULE_FIELDS, scheduleKind: 'custom', customCron: preset.cron }
  }
}

/** `ScheduleFieldsValue` → cron text, straight through `toCron` — what the
 *  dialog sends on submit. */
export function cronFromFields(fields: ScheduleFieldsValue): string {
  return toCron(presetFromFields(fields))
}

/** Cron text → `ScheduleFieldsValue` — what the edit dialog seeds the
 *  builder from. */
export function fieldsFromCron(cron: string): ScheduleFieldsValue {
  return fieldsFromPreset(fromCron(cron))
}
