#!/usr/bin/env bash
# nginx as the public entry point, reverse-proxying to the backend and frontend.
#
# Tuned for an AI workload: streaming responses are not buffered, and the read
# timeout is long enough for slow model generations.

_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
. "$_dir/lib/common.sh"
# shellcheck source=scripts/lib/config.sh
. "$_dir/lib/config.sh"

log_step "nginx"
require_root

apt_install "${PKGS_NGINX[@]}"

SITE_AVAILABLE="/etc/nginx/sites-available/$NGINX_SITE_NAME"
SITE_ENABLED="/etc/nginx/sites-enabled/$NGINX_SITE_NAME"

server_name="${NGINX_DOMAIN:-_}"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  log_info "[dry-run] would write $SITE_AVAILABLE (server_name $server_name)"
  log_info "[dry-run] would disable the default site and reload nginx"
  exit 0
fi

# --- site ---------------------------------------------------------------------
tmp_site="$(mktemp)"
cat >"$tmp_site" <<CONF
# Managed by ${APP_NAME}'s installer. Regenerated by scripts/64-install-nginx.sh
# — edit config in scripts/lib/config.sh, not here.

upstream ${APP_NAME}_backend {
    server 127.0.0.1:${BACKEND_PORT} fail_timeout=0;
}

upstream ${APP_NAME}_frontend {
    server 127.0.0.1:${FRONTEND_PORT} fail_timeout=0;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${server_name};

    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

    # Do not advertise the exact nginx version.
    server_tokens off;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    access_log /var/log/nginx/${NGINX_SITE_NAME}.access.log;
    error_log  /var/log/nginx/${NGINX_SITE_NAME}.error.log;

    # Let ACME HTTP-01 challenges through before any redirect.
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location /api/ {
        proxy_pass http://${APP_NAME}_backend;
        proxy_http_version 1.1;

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$connection_upgrade;

        # Token-by-token streaming (SSE / chunked) breaks if nginx buffers.
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout ${NGINX_PROXY_READ_TIMEOUT};
        proxy_send_timeout ${NGINX_PROXY_READ_TIMEOUT};
        chunked_transfer_encoding on;
    }

    location / {
        proxy_pass http://${APP_NAME}_frontend;
        proxy_http_version 1.1;

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$connection_upgrade;

        proxy_read_timeout ${NGINX_PROXY_READ_TIMEOUT};
    }
}
CONF

as_root install -m 0644 "$tmp_site" "$SITE_AVAILABLE"
rm -f "$tmp_site"
log_ok "Wrote $SITE_AVAILABLE"

# `Connection: upgrade` must only be sent when the client asked for an upgrade,
# otherwise plain keep-alive requests break. This map belongs at http level.
managed_block /etc/nginx/conf.d/upgrade-map.conf 0644 <<'CONF'
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
CONF

# --- enable ours, disable the distro default ---------------------------------
as_root ln -sfn "$SITE_AVAILABLE" "$SITE_ENABLED"
if [[ -e /etc/nginx/sites-enabled/default ]]; then
  as_root rm -f /etc/nginx/sites-enabled/default
  log_info "Disabled the default nginx site (kept in sites-available)"
fi

# --- validate before reloading ------------------------------------------------
if ! as_root nginx -t; then
  die "nginx rejected the generated config; nothing was reloaded. See the error above."
fi
log_ok "nginx config valid"

svc_enable_now nginx
svc_reload nginx

# --- TLS ----------------------------------------------------------------------
if [[ "$NGINX_ENABLE_TLS" == "1" ]]; then
  if [[ -z "$NGINX_DOMAIN" ]]; then
    log_warn "NGINX_ENABLE_TLS=1 but NGINX_DOMAIN is empty; skipping certificate issuance."
  else
    apt_install certbot python3-certbot-nginx
    certbot_args=(--nginx -d "$NGINX_DOMAIN" --non-interactive --agree-tos --redirect)
    if [[ -n "$NGINX_TLS_EMAIL" ]]; then
      certbot_args+=(-m "$NGINX_TLS_EMAIL")
    else
      certbot_args+=(--register-unsafely-without-email)
    fi
    log_info "Requesting a certificate for $NGINX_DOMAIN"
    if as_root certbot "${certbot_args[@]}"; then
      log_ok "TLS enabled for $NGINX_DOMAIN (renewal is handled by certbot.timer)"
    else
      log_warn "certbot failed. The site still serves plain HTTP."
      log_warn "Most likely cause: $NGINX_DOMAIN does not resolve to this host yet, or port 80 is closed."
    fi
  fi
elif [[ -n "$NGINX_DOMAIN" ]]; then
  log_info "TLS not requested. To enable it later:"
  log_info "  sudo apt install certbot python3-certbot-nginx"
  log_info "  sudo certbot --nginx -d $NGINX_DOMAIN --redirect"
else
  log_info "No NGINX_DOMAIN set; serving on any hostname over plain HTTP."
  log_info "Set NGINX_DOMAIN and NGINX_ENABLE_TLS=1 once DNS points at this host."
fi

log_ok "nginx ready — / -> :$FRONTEND_PORT, /api/ -> :$BACKEND_PORT"
