#!/usr/bin/env bash
# nginx, serving on the tailnet.
#
# No certbot and no Let's Encrypt: the system is reached over Tailscale, and
# WireGuard already encrypts every byte between client and host, so plain HTTP
# on tailscale0 is not sent in the clear. If a browser padlock is wanted,
# `tailscale serve` publishes this over HTTPS on the node's MagicDNS name with a
# certificate Tailscale provisions and renews. Set up at the end of this step,
# because it has to point at an nginx that is already listening.
#
# Runs after Tailscale so the MagicDNS name is known when the site is rendered.

_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
. "$_dir/lib/common.sh"
# shellcheck source=scripts/lib/config.sh
. "$_dir/lib/config.sh"

log_step "nginx"
require_root

apt_install "${PKGS_NGINX[@]}"

# An explicitly set domain wins and is remembered; otherwise the tailnet
# identity is re-detected on every run, so this fixes itself once Tailscale
# comes up.
sticky_recall NGINX_DOMAIN

SITE_AVAILABLE="/etc/nginx/sites-available/$NGINX_SITE_NAME"
SITE_ENABLED="/etc/nginx/sites-enabled/$NGINX_SITE_NAME"

# --- who are we on the tailnet? ----------------------------------------------
ts_names=()
ts_dns=""
if have tailscale && tailscale status >/dev/null 2>&1; then
  ts_dns="$(tailscale_dns_name || true)"
  while read -r endpoint; do
    [[ -n "$endpoint" ]] && ts_names+=("$endpoint")
  done < <(tailscale_endpoints)
fi

if [[ -n "$NGINX_DOMAIN" ]]; then
  server_name="$NGINX_DOMAIN"
  log_info "Using the configured server_name: $server_name"
elif (( ${#ts_names[@]} )); then
  server_name="${ts_names[*]}"
  log_ok "Detected tailnet identity: $server_name"
else
  server_name="_"
  log_warn "Tailscale is not up, so no MagicDNS name is known yet."
  log_warn "Serving as a catch-all; re-run this step once the node has joined:"
  log_warn "    sudo $INSTALL_SH --only nginx"
fi

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  log_info "[dry-run] would write $SITE_AVAILABLE (server_name $server_name)"
  log_info "[dry-run] would disable the default site and reload nginx"
  exit 0
fi

# --- site ---------------------------------------------------------------------
tmp_site="$(mktemp)"
cat >"$tmp_site" <<CONF
# Managed by ${APP_NAME}'s installer. Regenerated by scripts/66-install-nginx.sh
# — edit config in scripts/lib/config.sh, not here.
#
# Reached over Tailscale. Traffic on tailscale0 is WireGuard-encrypted, so this
# listens on plain HTTP; \`tailscale serve\` adds HTTPS on the MagicDNS name.

upstream ${APP_NAME}_backend {
    server 127.0.0.1:${BACKEND_PORT} fail_timeout=0;
}

upstream ${APP_NAME}_frontend {
    server 127.0.0.1:${FRONTEND_PORT} fail_timeout=0;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ${server_name};

    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};
    server_tokens off;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    access_log /var/log/nginx/${NGINX_SITE_NAME}.access.log;
    error_log  /var/log/nginx/${NGINX_SITE_NAME}.error.log;

    location /api/ {
        proxy_pass http://${APP_NAME}_backend;
        proxy_http_version 1.1;

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$connection_upgrade;

        # Token-by-token streaming (SSE / chunked) breaks if nginx buffers.
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout ${NGINX_PROXY_READ_TIMEOUT};
        proxy_send_timeout ${NGINX_PROXY_READ_TIMEOUT};
        chunked_transfer_encoding on;
    }

    location / {
        proxy_pass http://${APP_NAME}_frontend;
        proxy_http_version 1.1;

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$connection_upgrade;

        proxy_read_timeout ${NGINX_PROXY_READ_TIMEOUT};
    }
}
CONF

as_root install -m 0644 "$tmp_site" "$SITE_AVAILABLE"
rm -f "$tmp_site"
log_ok "Wrote $SITE_AVAILABLE"

# `Connection: upgrade` must only be sent when the client asked for an upgrade,
# otherwise plain keep-alive requests break. This map belongs at http level.
managed_block /etc/nginx/conf.d/upgrade-map.conf 0644 <<'CONF'
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
CONF

as_root ln -sfn "$SITE_AVAILABLE" "$SITE_ENABLED"
if [[ -e /etc/nginx/sites-enabled/default ]]; then
  as_root rm -f /etc/nginx/sites-enabled/default
  log_info "Disabled the default nginx site (kept in sites-available)"
fi

if ! as_root nginx -t; then
  die "nginx rejected the generated config; nothing was reloaded. See the error above."
fi
log_ok "nginx config valid"

svc_enable_now nginx
svc_reload nginx

setting_remember NGINX_DOMAIN "$NGINX_DOMAIN"

# --- how to reach it ----------------------------------------------------------
log_ok "nginx ready — / -> :$FRONTEND_PORT, /api/ -> :$BACKEND_PORT"

# --- publish over HTTPS on the tailnet ---------------------------------------
served=0
if [[ "$TAILSCALE_SERVE" == "1" ]]; then
  if ! have tailscale || ! tailscale status >/dev/null 2>&1; then
    log_info "Tailscale is not connected; skipping 'tailscale serve'."
    log_info "Once the node joins, re-run:  sudo $INSTALL_SH --only nginx"
  else
    log_info "Publishing nginx over HTTPS with 'tailscale serve'"
    if serve_out="$(as_root tailscale serve --bg "$TAILSCALE_SERVE_PORT" 2>&1)"; then
      served=1
      log_ok "Tailscale is terminating HTTPS; it manages and renews the certificate."
    else
      log_warn "'tailscale serve' failed — nginx still serves plain HTTP on the tailnet:"
      printf '%s\n' "$serve_out" | sed 's/^/    /' >&2
      log_warn "Most often this means HTTPS certificates are not enabled for the tailnet."
      log_warn "Enable them in the admin console (DNS -> HTTPS Certificates), then:"
      log_warn "    sudo tailscale serve --bg $TAILSCALE_SERVE_PORT"
    fi
  fi
fi

# --- how to reach it ----------------------------------------------------------
if (( ${#ts_names[@]} )); then
  log_info "Reachable on the tailnet at:"
  if (( served )) && [[ -n "${ts_dns:-}" ]]; then
    log_info "    https://${ts_dns}/"
  fi
  for n in "${ts_names[@]}"; do
    log_info "    $(tailscale_url "$n")"
  done
fi
